version: '3.7'
services:
  kalilinux:
    hostname: kalilinux.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'lucasmullers/kalilinux:${VERSION:-latest}'
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - SHELL=/bin/bash
      - PASSWORD=${PASSWORD:-kali}
    volumes:
      - ~/Estudos/kali:/root/kali
    entrypoint: ["/bin/bash", "/startup.sh"]

volumes:
  data: {}